### ISSUE TITLE
Small bug in parsing

### ISSUE THREAD

**Issue by aditya95sriram** [gleiss/server-vampire#1]
I'm using Vampire v4.7 (commit [7c473653c](https://github.com/vprover/vampire/commit/7c473653c910f56ee5bda67fd58b2b0b3e0308f6)), and the `model/parsing.py` falters with the `line_type` identification. For instance, the `line_type` is reported as `" replaced by"` instead of `"replaced by"` which then confuses [gleiss/saturation-visualization](https://github.com/gleiss/saturation-visualization) causing it to get stuck with the message "Waiting for Vampire..." showing.

Steps to reproduce error:
1. Start vampire-server locally
2. Open [saturation-visualization app](https://gleiss.github.io/saturation-visualization/)
3. Set input language to TPTP and fill the input field with the following:

```
fof(define_less,axiom,(
    ![X,Y] : (less(X,Y) => (? [Z] : (less(X,Z) & less(Z,Y)))) )).

fof(derive_more,axiom,(
    ![X,Y] : (less(X,Y) <=> more(Y,X)) )).

fof(more_dense,conjecture,(
    ![X,Y] : (more(X,Y) => (? [Z] : (more(X,Z) & more(Z,Y)))) )).
```
4. Click "Find proof"

**Expected behavior:** Screen stuck on "Waiting for Vampire..."

**Comment by gleiss** [comment]
Thank you for your input, this repository is not actively maintained anymore
